---
Name: Anzrsai
After: 'framework/*','cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
Email:
  admin_email: 'anzrsai@anzrsai.org'
SSViewer:
  theme: 'anzrsai'
Director:
  dev_servers:
    - anzrsai.localdev
    - anzrsai.local
    - anzrsai.ssdev.delta.internetrix.net.staging.internetrix.anchor.net.au
