<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `anzrsai_fs`
//

// `anzrsai_fs`.`contact`
$contact = array(
  array('id' => '1','firstname' => 'Mike','surname' => 'David','email' => 'mike@internetrix.com.au','mobile' => '0402965250','fax' => '0242261985','password' => 'mike123','newsletter' => '1','category' => 'admin'),
  array('id' => '2','firstname' => 'Daniel','surname' => 'Rowan','email' => 'daniel.rowan@internetrix.com.au','mobile' => '0414','fax' => '4226 1985','password' => 'dan123','newsletter' => '0','category' => 'member'),
  array('id' => '3','firstname' => 'Tim','surname' => 'Lawson','email' => 'tim.lawson@internetrix.com.au','mobile' => '','fax' => '','password' => 'tim123','newsletter' => '1','category' => 'council'),
  array('id' => '4','firstname' => 'Geoff','surname' => 'McQueen','email' => 'geoff.mcqueen@internetrix.com.au','mobile' => '','fax' => '','password' => 'geoff123','newsletter' => '0','category' => 'public'),
  array('id' => '6','firstname' => 'David','surname' => 'Clarke','email' => 'david.clarke@internetrix.com.au','mobile' => NULL,'fax' => NULL,'password' => 'dc123','newsletter' => '1','category' => 'public'),
  array('id' => '8','firstname' => 'Ben','surname' => 'Angus','email' => 'ben@internetrix.com.au','mobile' => 'GENERAL','fax' => 'GENERAL','password' => 'ben123','newsletter' => '1','category' => 'council'),
  array('id' => '30','firstname' => 'John','surname' => 'Martin','email' => 'John.Martin@latrobe.edu.au','mobile' => '','fax' => 'conf2012 standard','password' => 'John123','newsletter' => '1','category' => 'member'),
  array('id' => '546','firstname' => 'Kingsley','surname' => 'Haynes','email' => 'khaynes@gmu.edu','mobile' => '','fax' => '2013','password' => 'kingsley123','newsletter' => '1','category' => 'member'),
  array('id' => '44','firstname' => 'Roy','surname' => 'Powell','email' => 'roy@care.net.au','mobile' => 'life','fax' => '','password' => 'Roy123','newsletter' => '1','category' => 'member'),
  array('id' => '45','firstname' => 'Robert (Bob)','surname' => 'Stimson','email' => 'rstimson@unimelb.edu.au','mobile' => 'life','fax' => '','password' => 'Robert123','newsletter' => '1','category' => 'council'),
  array('id' => '558','firstname' => 'Natalia','surname' => 'Dekovic','email' => 'ndekovic@gmail.com','mobile' => '','fax' => '','password' => 'nd4611','newsletter' => '1','category' => 'public'),
  array('id' => '629','firstname' => 'Bruce','surname' => 'Wilson','email' => 'bruce.wilson@rmit.edu.au','mobile' => 'ind2014','fax' => '','password' => 'Bruce123','newsletter' => '1','category' => 'council'),
  array('id' => '415','firstname' => 'David','surname' => 'Wilson','email' => 'dawilson@aut.ac.nz','mobile' => '','fax' => '2011','password' => 'david123','newsletter' => '1','category' => 'member'),
  array('id' => '81','firstname' => 'Roberta','surname' => 'Collins','email' => 'robbie@uow.edu.au','mobile' => '','fax' => 'conf 2012 standard','password' => 'Robbie123','newsletter' => '1','category' => 'member'),
  array('id' => '410','firstname' => 'Library','surname' => 'University of Southern Queensland','email' => 'libes@usq.edu.au','mobile' => 'mar2012','fax' => '','password' => 'usq123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '426','firstname' => 'University of Southern Queensland','surname' => '','email' => 'davisan@usq.edu.au','mobile' => '','fax' => '','password' => 'usq123','newsletter' => '1','category' => 'SRA'),
  array('id' => '90','firstname' => 'Paul','surname' => 'Dalziel','email' => 'dalzielp@lincoln.ac.nz','mobile' => '','fax' => 'conf2012 standard','password' => 'Paul123','newsletter' => '1','category' => 'council'),
  array('id' => '102','firstname' => 'Robyn','surname' => 'Eversole','email' => 'Robyn.Eversole@utas.edu.au','mobile' => 'conf06','fax' => '','password' => 'Robyn123','newsletter' => '1','category' => 'council'),
  array('id' => '412','firstname' => 'SERIALS ILLS','surname' => 'University of Technology Sydney','email' => 'ill@lib.uts.edu.au','mobile' => 'jan2012','fax' => '','password' => 'UTS','newsletter' => '1','category' => 'AJRS'),
  array('id' => '104','firstname' => 'Ifor','surname' => 'Ffowcs-Williams','email' => 'e4@clusternavigators.com','mobile' => '2013','fax' => '','password' => 'Ifor123','newsletter' => '1','category' => 'member'),
  array('id' => '521','firstname' => 'Informit','surname' => 'RMIT Publishing','email' => 'production@rmitpublishing.com.au','mobile' => '','fax' => 'licence agreement','password' => 'rmit123','newsletter' => '1','category' => 'member'),
  array('id' => '114','firstname' => 'Rolf','surname' => 'Gerritsen','email' => 'Rolf.Gerritsen@cdu.edu.au','mobile' => '','fax' => '0910','password' => 'Rolf123','newsletter' => '1','category' => 'council'),
  array('id' => '527','firstname' => 'Cunningham Library','surname' => 'CSIRO','email' => 'infosupport@csiro.au','mobile' => 'SR2010','fax' => '','password' => 'csiro123','newsletter' => '0','category' => 'SRA'),
  array('id' => '151','firstname' => 'John','surname' => 'Madden','email' => 'john.madden@monash.edu','mobile' => '','fax' => '2013','password' => 'John123','newsletter' => '1','category' => 'member'),
  array('id' => '458','firstname' => 'Library Serials','surname' => 'Central Queensland University','email' => 'cqulibrary@cqu.edu.au','mobile' => '2008','fax' => ' library-serials@cqu','password' => 'cqu123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '560','firstname' => 'Tony','surname' => 'Irish','email' => 'tonyi@sedadvisory.com','mobile' => 'conf2012 standard','fax' => '','password' => 'tony123','newsletter' => '1','category' => 'member'),
  array('id' => '168','firstname' => 'Fiona','surname' => 'McKenzie','email' => 'Fiona.McKenzie@dpcd.vic.gov.au','mobile' => 'conf2012 standard','fax' => '','password' => 'Fiona123','newsletter' => '1','category' => 'member'),
  array('id' => '173','firstname' => 'Julian','surname' => 'Morison','email' => 'jbmorison@econsearch.com.au','mobile' => 'conf09','fax' => '','password' => 'Julian123','newsletter' => '1','category' => 'member'),
  array('id' => '631','firstname' => 'Ryan','surname' => 'Daniel','email' => 'ryan.daniel@jcu.edu.au','mobile' => 'ind2014','fax' => '','password' => 'ryan123','newsletter' => '1','category' => 'member'),
  array('id' => '184','firstname' => 'Tony','surname' => 'O\'Malley','email' => 'Tony.Omalley@adelaide.on.net','mobile' => 'conf2012 standard','fax' => '','password' => 'Tony123','newsletter' => '1','category' => 'council'),
  array('id' => '465','firstname' => 'Library','surname' => 'Southern Cross University','email' => 'libdbuser@scu.edu.au','mobile' => 'jan2012','fax' => '','password' => 'scu123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '190','firstname' => 'Jacques','surname' => 'Poot','email' => 'jpoot@waikato.ac.nz','mobile' => '2013','fax' => '','password' => 'Jacques123','newsletter' => '1','category' => 'member'),
  array('id' => '463','firstname' => 'Library Officer ','surname' => 'Latrobe Uni Bendigo','email' => 'A.Maxwell@latrobe.edu.au','mobile' => '','fax' => '','password' => 'Bendigo123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '462','firstname' => 'Flinders University','surname' => 'Serials Central Library','email' => 'eradmin@flinders.edu.au','mobile' => 'jan2012','fax' => '','password' => 'flinders123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '459','firstname' => 'ZBW','surname' => 'Deutsche Zentralbibliotek ','email' => 'c.harder@zbw.eu','mobile' => '2013','fax' => '','password' => 'zbw123','newsletter' => '0','category' => 'AJRS'),
  array('id' => '627','firstname' => 'Tasmiha','surname' => 'Tarafder','email' => 'tasmiha.tarafder@canberra.edu.au','mobile' => 'student2014','fax' => '','password' => 'Tasmiha123','newsletter' => '1','category' => 'member'),
  array('id' => '534','firstname' => 'Vanessa Lewis','surname' => 'South West Development Corporation ','email' => 'vanessa.lewis@swdc.wa.gov.au','mobile' => '0910 institutional','fax' => '','password' => 'swdc123','newsletter' => '0','category' => 'member'),
  array('id' => '211','firstname' => 'Glen','surname' => 'Searle','email' => 'g.searle@uq.edu.au','mobile' => '2013','fax' => '','password' => 'Glen123','newsletter' => '1','category' => 'member'),
  array('id' => '591','firstname' => 'Susan','surname' => 'Zhang','email' => 'susan.zhang@internetrix.com.au','mobile' => '','fax' => '','password' => 'susan123','newsletter' => '1','category' => 'admin'),
  array('id' => '217','firstname' => 'Tony','surname' => 'Sorensen','email' => 'tony.sorensen@une.edu.au','mobile' => '','fax' => 'conf2012 standard','password' => 'Tony123','newsletter' => '1','category' => 'council'),
  array('id' => '419','firstname' => 'Alex','surname' => 'Kerr','email' => 'kerra@ozemail.com','mobile' => '','fax' => 'life','password' => '','newsletter' => '1','category' => 'member'),
  array('id' => '522','firstname' => 'NATSEM','surname' => '','email' => 'reception@natsem.canberra.edu.au','mobile' => 'instutute 0910','fax' => '','password' => 'natsem123','newsletter' => '1','category' => 'member'),
  array('id' => '529','firstname' => 'Matthew ','surname' => 'Strand','email' => 'Matthew.Strand@proquest.com','mobile' => '','fax' => 'Proquest','password' => 'Matt123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '530','firstname' => 'Paul','surname' => 'McPhee','email' => 'p.mcphee@ballarat.edu.au','mobile' => '','fax' => '2012','password' => 'Paul123','newsletter' => '1','category' => 'member'),
  array('id' => '595','firstname' => 'Bradley','surname' => 'Braithwaite','email' => 'bradley@uow.edu.au','mobile' => '','fax' => 'conf 2012 standard','password' => 'brad123','newsletter' => '1','category' => 'member'),
  array('id' => '561','firstname' => 'Suzanne','surname' => 'Keene','email' => 'suzanne.keene@rdv.vic.gov.au','mobile' => '2013','fax' => '','password' => 'suzanne123','newsletter' => '1','category' => 'member'),
  array('id' => '421','firstname' => 'Kevin','surname' => 'O\'Connor','email' => 'kevino@unimelb.edu.au','mobile' => '','fax' => 'life','password' => '','newsletter' => '1','category' => 'member'),
  array('id' => '422','firstname' => 'UNSW','surname' => 'Library','email' => 'eraccess@unsw.edu.au ','mobile' => '','fax' => '','password' => 'unsw123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '597','firstname' => 'Brett','surname' => 'Davis ','email' => 'brettd@sedadvisory.com','mobile' => '','fax' => 'conf2012 standard','password' => 'brett123','newsletter' => '1','category' => 'member'),
  array('id' => '430','firstname' => 'Paul','surname' => 'Collits','email' => 'paul.collits@usq.edu.au','mobile' => '','fax' => 'conf09','password' => 'paul123','newsletter' => '1','category' => 'council'),
  array('id' => '593','firstname' => 'Anne','surname' => 'Garnett','email' => 'a.garnett@murdoch.edu.au','mobile' => 'indiv2013','fax' => '','password' => 'anne123','newsletter' => '1','category' => 'member'),
  array('id' => '567','firstname' => 'Wej','surname' => 'Paradice','email' => 'wej@hvrf.com.au','mobile' => '2013','fax' => '','password' => 'wej123','newsletter' => '1','category' => 'member'),
  array('id' => '423','firstname' => 'Sally','surname' => 'Weller','email' => 'sally.weller@vu.edu.au','mobile' => 'conf2010','fax' => '+613 9919 1125','password' => 'mspsb567','newsletter' => '0','category' => 'member'),
  array('id' => '318','firstname' => 'mike','surname' => 'david','email' => 'mike1@internetrix.com.au','mobile' => '0402965250','fax' => '42261985','password' => 'mike123','newsletter' => '1','category' => 'SRA'),
  array('id' => '319','firstname' => 'mike','surname' => 'david','email' => 'michael.david@internetrix.com.au','mobile' => '','fax' => '','password' => 'mike','newsletter' => '1','category' => 'SRA'),
  array('id' => '320','firstname' => 'Eamonn','surname' => 'Bell','email' => 'eamonn.bell@internetrix.com.au','mobile' => '','fax' => '','password' => 'eamonn','newsletter' => '0','category' => 'admin'),
  array('id' => '619','firstname' => 'Bradley','surname' => 'Jorgensen','email' => 'b.jorgensen@latrobe.edu.au','mobile' => '','fax' => '','password' => 'brad123','newsletter' => '1','category' => 'member'),
  array('id' => '460','firstname' => 'Yonsei University','surname' => 'Library','email' => 'MUNSH@YONSEI.AC.KR','mobile' => '2013','fax' => '','password' => 'yonsei123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '461','firstname' => 'ServiceFirst Library.  ','surname' => 'Dept of Services, Technology & Administration','email' => 'librarian@servicefirst.nsw.gov.au','mobile' => 'jan2012','fax' => '','password' => 'dnr123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '557','firstname' => 'Sonya','surname' => 'Glavac','email' => 'sglavac@une.edu.au','mobile' => '','fax' => 'ajrs editor','password' => 'sonya123','newsletter' => '1','category' => 'council'),
  array('id' => '411','firstname' => 'I&RD','surname' => 'Ministry of Economic Development','email' => 'cally.ward@med.govt.nz','mobile' => '','fax' => 'institute subs 07','password' => 'IRD123','newsletter' => '0','category' => 'SRA'),
  array('id' => '464','firstname' => 'Neil','surname' => 'Grant','email' => 'ngrant@uow.edu.au','mobile' => '','fax' => '','password' => 'balc9991','newsletter' => '1','category' => 'public'),
  array('id' => '363','firstname' => 'Trevor','surname' => 'Halamicek','email' => 'thalamicek@bigpond.com','mobile' => '0428876511','fax' => '','password' => 'dalmatian','newsletter' => '1','category' => 'public'),
  array('id' => '365','firstname' => 'Lynne','surname' => 'Moran','email' => 'lynnemoran@southcom.com.au','mobile' => '0417528116','fax' => NULL,'password' => 'Michael2','newsletter' => '1','category' => 'public'),
  array('id' => '366','firstname' => 'Darren','surname' => 'Holloway','email' => 'd.holloway@unsw.edu.au','mobile' => NULL,'fax' => NULL,'password' => 'dh4474','newsletter' => '1','category' => 'public'),
  array('id' => '367','firstname' => 'Hazel','surname' => 'Jones','email' => 'anzrsai@anzrsai.org','mobile' => '','fax' => '','password' => 'hazel123','newsletter' => '1','category' => 'admin'),
  array('id' => '368','firstname' => 'Sian','surname' => 'Nivison','email' => 'siannivison@yahoo.com','mobile' => '0428 778375','fax' => '0740694523','password' => 'st0mper','newsletter' => '1','category' => 'public'),
  array('id' => '590','firstname' => 'James','surname' => 'Rowe','email' => 'james.rowe@ktc.nt.gov.au','mobile' => '','fax' => '2013','password' => 'james123','newsletter' => '1','category' => 'council'),
  array('id' => '603','firstname' => 'Jessica','surname' => 'Oliver','email' => 'jbaxter@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => '','newsletter' => '1','category' => 'member'),
  array('id' => '371','firstname' => 'Greg','surname' => 'Jones','email' => 'gjones@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'greg123','newsletter' => '1','category' => 'council'),
  array('id' => '373','firstname' => 'Elizabeth','surname' => 'Jarrett','email' => 'elizabeth.jarrett@envbop.govt.nz','mobile' => '','fax' => '','password' => 'envbop123','newsletter' => '1','category' => 'SRA'),
  array('id' => '376','firstname' => 'Yigezu','surname' => 'Hirut','email' => 'library@dotars.gov.au','mobile' => '','fax' => '','password' => 'dotars123','newsletter' => '0','category' => 'AJRS'),
  array('id' => '380','firstname' => 'Anne','surname' => 'Mendiolea','email' => 'corporatelibrary@townsville.qld.gov.au','mobile' => '','fax' => '0747279237','password' => 'corplib','newsletter' => '0','category' => 'public'),
  array('id' => '543','firstname' => 'Robyn','surname' => 'Institute for Regional Development','email' => 'IRD.Enquiries@utas.edu.au','mobile' => '2012 institute','fax' => '','password' => 'IRD123','newsletter' => '1','category' => 'member'),
  array('id' => '466','firstname' => 'Curtin','surname' => 'Uni of Technology','email' => 'library-journals@curtin.edu.au','mobile' => 'jan2012','fax' => '','password' => 'curtin123','newsletter' => '0','category' => 'AJRS'),
  array('id' => '467','firstname' => 'Gale ','surname' => 'Licence Agreement','email' => 'electronic.feed@cengage.com','mobile' => '','fax' => '','password' => 'gale123','newsletter' => '0','category' => 'AJRS'),
  array('id' => '468','firstname' => 'Karin','surname' => 'Trounce','email' => 'trouncek@agr.gc.ca','mobile' => '613-759-6535','fax' => '613-759-6763','password' => 'm23m3nt0','newsletter' => '1','category' => 'public'),
  array('id' => '469','firstname' => 'Ebsco','surname' => 'Publishing','email' => 'eppubdata@epnet.com','mobile' => '','fax' => '','password' => 'ebsco123','newsletter' => '0','category' => 'AJRS'),
  array('id' => '562','firstname' => 'Greg','surname' => 'Kerr','email' => 'gregkerr@uowdubai.ac.ae','mobile' => '2012','fax' => '','password' => 'greg123','newsletter' => '1','category' => 'council'),
  array('id' => '618','firstname' => 'Mark','surname' => 'Jones','email' => 'mark@aej.com.au','mobile' => '','fax' => '','password' => 'Mark123','newsletter' => '1','category' => 'member'),
  array('id' => '538','firstname' => 'Andrew','surname' => 'Beer','email' => 'andrew.beer@adelaide.edu.au','mobile' => '2013','fax' => '','password' => 'andrew123','newsletter' => '1','category' => 'member'),
  array('id' => '625','firstname' => 'Annette','surname' => 'Willians','email' => 'awilliams@wollongong.nsw.gov.au','mobile' => 'student2014','fax' => '','password' => 'annette123','newsletter' => '1','category' => 'member'),
  array('id' => '480','firstname' => 'Andrew ','surname' => 'Cruickshank','email' => 'andrewcruickshank@bigpond.com','mobile' => '2013','fax' => '','password' => 'andrew123','newsletter' => '1','category' => 'member'),
  array('id' => '630','firstname' => 'John','surname' => 'Rolfe','email' => 'j.rolfe@cqu.edu.au','mobile' => 'inst2014','fax' => '','password' => 'john123','newsletter' => '1','category' => 'member'),
  array('id' => '483','firstname' => 'Ishma','surname' => 'Soepriadi','email' => 'ishmafathimah@yahoo.com','mobile' => '+6281320468467','fax' => '','password' => 'katasakti','newsletter' => '0','category' => 'public'),
  array('id' => '486','firstname' => 'Matthew','surname' => 'Campbell-Ellis','email' => 'mattce@gmail.com','mobile' => '','fax' => '0910','password' => 'matt123','newsletter' => '1','category' => 'member'),
  array('id' => '596','firstname' => 'Fiona','surname' => 'Davey','email' => 'fionad@sedadvisory.com','mobile' => '','fax' => 'conf2012 standard','password' => 'fiona123','newsletter' => '1','category' => 'member'),
  array('id' => '626','firstname' => 'Karen','surname' => 'Plane','email' => 'karenplane@adcm.com.au','mobile' => 'standard2014','fax' => '','password' => 'karen123','newsletter' => '1','category' => 'member'),
  array('id' => '516','firstname' => 'Lisa','surname' => 'Conolly','email' => 'lisa.conolly@abs.gov.au','mobile' => '','fax' => '2013','password' => 'lisa123','newsletter' => '1','category' => 'member'),
  array('id' => '622','firstname' => 'Wayne','surname' => 'Graham','email' => 'wgraham@usc.edu.au','mobile' => '','fax' => '','password' => 'wayne123','newsletter' => '1','category' => 'council'),
  array('id' => '518','firstname' => 'Helen','surname' => 'Dineen','email' => 'helen.dineen@rdv.vic.gov.au','mobile' => '','fax' => '','password' => 'helen123','newsletter' => '1','category' => 'AJRS'),
  array('id' => '519','firstname' => 'Deakin','surname' => 'Library','email' => 'electronic.access@deakin.edu.au','mobile' => 'feb2012','fax' => '','password' => 'deakin','newsletter' => '1','category' => 'AJRS'),
  array('id' => '568','firstname' => 'Dean','surname' => 'Carson','email' => 'dean.carson@flinders.edu.au','mobile' => 'conf2012 standard','fax' => '','password' => 'dean123','newsletter' => '1','category' => 'member'),
  array('id' => '559','firstname' => 'Bligh','surname' => 'Grant','email' => 'bgrant5@une.edu.au','mobile' => '2013','fax' => '','password' => 'bligh123','newsletter' => '0','category' => 'member'),
  array('id' => '594','firstname' => 'Anne','surname' => 'Abraham','email' => 'a.abraham@uws.edu.au','mobile' => '','fax' => 'conf 2012 standard','password' => 'anne123','newsletter' => '1','category' => 'member'),
  array('id' => '570','firstname' => 'Lea','surname' => 'Coates','email' => 'Lea.Coates@utas.edu.au','mobile' => 'stud2012','fax' => '','password' => 'lea123','newsletter' => '1','category' => 'member'),
  array('id' => '572','firstname' => 'Michelle','surname' => 'Graymore','email' => 'm.graymore@ballarat.edu.au','mobile' => '2013','fax' => '','password' => 'michelle123','newsletter' => '1','category' => 'member'),
  array('id' => '573','firstname' => 'Anthony','surname' => 'Hogan','email' => 'anthony.hogan@canberra.edu.au','mobile' => 'conf2012 standard','fax' => '','password' => 'anthony123','newsletter' => '1','category' => 'member'),
  array('id' => '574','firstname' => 'Kim','surname' => 'Houghton','email' => 'kim@economicsolutions.com.au','mobile' => '2013','fax' => '','password' => 'kim123','newsletter' => '1','category' => 'member'),
  array('id' => '577','firstname' => 'Dongwook','surname' => 'Park','email' => 'dreamwood2@gmail.com','mobile' => 'student 2013','fax' => '','password' => 'park123','newsletter' => '0','category' => 'member'),
  array('id' => '628','firstname' => 'Delwar','surname' => 'Akbar','email' => 'd.akbar@cqu.edu.au','mobile' => 'inst2014','fax' => '','password' => 'delwar123','newsletter' => '1','category' => 'council'),
  array('id' => '624','firstname' => 'Ion Lucian','surname' => 'Ceapraz','email' => 'lucian.ceapraz@lasalle-beauvais.fr','mobile' => '','fax' => '','password' => 'Ion123','newsletter' => '1','category' => 'member'),
  array('id' => '623','firstname' => 'Mike','surname' => 'Hefferan','email' => 'mheffera@usc.edu.au','mobile' => '','fax' => '','password' => 'Mike123','newsletter' => '1','category' => 'member'),
  array('id' => '620','firstname' => 'Susan','surname' => 'Haynes','email' => 'shlibrary1009@gmail.com','mobile' => '','fax' => '','password' => 'Susan123','newsletter' => '1','category' => 'member'),
  array('id' => '621','firstname' => 'Jonathan','surname' => 'Corcoran','email' => 'jj.corcoran@uq.edu.au','mobile' => '','fax' => '','password' => 'Jon123','newsletter' => '1','category' => 'member'),
  array('id' => '583','firstname' => 'Susan and colleagues','surname' => 'Sustainable Regional Development programme CQU','email' => 's.kinnear@cqu.edu.au','mobile' => 'inst2012','fax' => '','password' => 'cqu123','newsletter' => '1','category' => 'member'),
  array('id' => '585','firstname' => 'Yogi','surname' => 'Vidyattama','email' => 'yogi.vidyattama@natsem.canberra.gov.au ','mobile' => '','fax' => '','password' => 'yogi123','newsletter' => '1','category' => 'council'),
  array('id' => '589','firstname' => 'Wendy','surname' => 'Newman','email' => 'wendy.newman@wheatbelt.wa.gov.au ','mobile' => '2012Institute','fax' => '','password' => 'wheat123','newsletter' => '1','category' => 'member'),
  array('id' => '592','firstname' => 'Christopher','surname' => 'McDonald','email' => 'chris.mcdonald@monash.edu','mobile' => 'indiv 2013','fax' => '','password' => 'chris123','newsletter' => '1','category' => 'member'),
  array('id' => '598','firstname' => 'Natalie','surname' => 'Akmacic','email' => 'akmacic@uow.edu.au','mobile' => 'conf2012 studebt','fax' => '','password' => 'natalie123','newsletter' => '1','category' => 'member'),
  array('id' => '599','firstname' => 'Eve-Marie','surname' => 'Davie','email' => 'evedavie@iinet.net.au','mobile' => 'conf2012 student','fax' => '','password' => 'eve123','newsletter' => '1','category' => 'member'),
  array('id' => '600','firstname' => 'Clifford','surname' => 'Lewis','email' => 'cll105@uowmail.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'clifford123','newsletter' => '1','category' => 'member'),
  array('id' => '601','firstname' => 'Ashkan','surname' => 'Masouman','email' => 'am983@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'ashkan123','newsletter' => '1','category' => 'member'),
  array('id' => '602','firstname' => 'Simon','surname' => 'Masselos','email' => 'sm336@uowmail.edu.au','mobile' => 'conf2012 studwnt','fax' => '','password' => 'simon123','newsletter' => '1','category' => 'member'),
  array('id' => '604','firstname' => 'Adrienne','surname' => 'Jouver','email' => 'adrienne@econlit.org','mobile' => 'econlit database','fax' => '','password' => 'econlit','newsletter' => '1','category' => 'AJRS'),
  array('id' => '605','firstname' => 'Lisa','surname' => 'Moutzouris','email' => 'lisa.moutzouris@abs.gov.au','mobile' => '2013','fax' => '','password' => 'lisa123','newsletter' => '1','category' => 'member'),
  array('id' => '606','firstname' => 'Alison','surname' => 'Dalziel','email' => 'alison.dalziel@wearelocalise.com','mobile' => '2013','fax' => '','password' => 'alison123','newsletter' => '1','category' => 'member'),
  array('id' => '607','firstname' => 'Katrina','surname' => 'Edillor','email' => 'katrina@wfa.org.au','mobile' => '','fax' => '2013','password' => 'Katrina123','newsletter' => '1','category' => 'member'),
  array('id' => '608','firstname' => 'Anthony','surname' => 'Kent','email' => 'anthony.kent@vu.edu.au','mobile' => '2013','fax' => '','password' => 'Anthony123','newsletter' => '1','category' => 'member'),
  array('id' => '609','firstname' => 'Heather','surname' => 'Zeppell','email' => 'heather.zeppel@usq.edu.au','mobile' => '2013','fax' => '','password' => 'Heather123','newsletter' => '1','category' => 'member'),
  array('id' => '610','firstname' => 'Allison','surname' => 'Bradford','email' => 'amb576@uow.edu.au','mobile' => 'student2013','fax' => '','password' => 'Allison123','newsletter' => '1','category' => 'member'),
  array('id' => '611','firstname' => 'Rose','surname' => 'Crothers','email' => 'rose_crothers@uow.edu.au','mobile' => 'student2013','fax' => '','password' => 'Rose123','newsletter' => '1','category' => 'member'),
  array('id' => '612','firstname' => 'Margaret','surname' => 'Le','email' => 'ml687@uow.edu.au','mobile' => 'student2013','fax' => '','password' => 'Margaret123','newsletter' => '1','category' => 'member'),
  array('id' => '613','firstname' => 'Noelene','surname' => 'Rudolph','email' => 'nsr895@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'Noelene12','newsletter' => '1','category' => 'member'),
  array('id' => '614','firstname' => 'Susan','surname' => 'Savage','email' => 'sas358@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'Susan123','newsletter' => '1','category' => 'member'),
  array('id' => '615','firstname' => 'Rebekah','surname' => 'Schulz','email' => 'rs882W@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'Rebekah123','newsletter' => '1','category' => 'member'),
  array('id' => '616','firstname' => 'Kate','surname' => 'Speare','email' => 'kls999@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'Kate123','newsletter' => '1','category' => 'member'),
  array('id' => '617','firstname' => 'Jenny','surname' => 'Thompson','email' => 'jmt960@uow.edu.au','mobile' => 'conf2012 student','fax' => '','password' => 'Jenny123','newsletter' => '1','category' => 'member')
);
