<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database `uglyfish`
//

// `uglyfish`.`OnlineStore`
$OnlineStore = array(
  array('ID' => '1','ClassName' => 'OnlineStore','Created' => '2012-02-15 15:11:10','LastEdited' => '2012-11-01 14:00:47','Title' => 'Fishing Tackle Shop','Email' => 'online@fishingtackleshop.com.au ','Website' => 'http://www.fishingtackleshop.com.au/categories/uglyfish-eyewear-sunglasses?sort=priceasc','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '6','ClassName' => 'OnlineStore','Created' => '2012-02-22 14:25:15','LastEdited' => '2013-02-22 10:13:45','Title' => 'Just Sunnies','Email' => 'info@justsunnies.com.au','Website' => 'http://www.justsunnies.com.au/m_ugly-fish/','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '3','ClassName' => 'OnlineStore','Created' => '2012-02-22 14:09:26','LastEdited' => '2013-02-22 10:14:20','Title' => 'Get Your Sunnies Online','Email' => 'info@getyoursunniesonline.com','Website' => 'http://www.getyoursunniesonline.com/shop/listings/ugly-fish-eyewear/','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '4','ClassName' => 'OnlineStore','Created' => '2012-02-22 14:13:33','LastEdited' => '2013-10-16 11:41:19','Title' => 'Kamikaze Fishing Tackle Systems','Email' => 'sales@bluewaterfishingdownunder.com','Website' => 'http://www.kamikazefishing.com/c/fishing-accessories/eyewear/1615','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '21','ClassName' => 'OnlineStore','Created' => '2013-07-02 09:31:08','LastEdited' => '2013-07-02 09:32:59','Title' => 'RACQ **Member Discounts Apply**','Email' => 'onlineshop@racq.com.au','Website' => 'http://onlineshop.racq.com.au/','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '7','ClassName' => 'OnlineStore','Created' => '2012-02-23 15:56:00','LastEdited' => '2012-11-01 13:53:02','Title' => 'Hot Chilli Source','Email' => 'info@hotchillisource.com.au','Website' => 'http://www.safetyglasses.com.au/product-range/ugly-fish.html?___store=default','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '0','Prescription' => '0','Safety' => '1'),
  array('ID' => '10','ClassName' => 'OnlineStore','Created' => '2012-03-28 13:09:28','LastEdited' => '2012-03-28 13:10:24','Title' => 'NRMA **Member Discounts Apply**','Email' => 'onlineshop@mynrma.com.au','Website' => 'http://www.mynrma.com.au/shop','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '9','ClassName' => 'OnlineStore','Created' => '2012-03-14 12:06:17','LastEdited' => '2013-09-17 09:59:39','Title' => 'Mo Tackle','Email' => 'sales@motackle.com.au','Website' => 'http://www.motackle.com.au/fishing/sunglasses.html?manufacturer=16286','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '11','ClassName' => 'OnlineStore','Created' => '2012-04-05 16:22:23','LastEdited' => '2012-04-05 16:22:23','Title' => 'A. Ugly Fish Eyewear ebay store','Email' => 'orders@piranhaeyewear.com','Website' => 'http://stores.ebay.com.au/uglyfisheyewear','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '1','Polarised' => '1','Prescription' => '1','Safety' => '1'),
  array('ID' => '12','ClassName' => 'OnlineStore','Created' => '2012-06-20 10:47:37','LastEdited' => '2012-06-20 10:47:37','Title' => 'W & W Cycles - Germany','Email' => NULL,'Website' => 'http://www.wwag.com/cgi-bin/WebObjects/WebSite.woa/wa/DirectAction?page=%2131531','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '1','Polarised' => '0','Prescription' => '0','Safety' => '0'),
  array('ID' => '15','ClassName' => 'OnlineStore','Created' => '2012-08-14 16:13:41','LastEdited' => '2013-03-08 12:50:32','Title' => 'Hurtle Gear','Email' => NULL,'Website' => 'http://www.hurtlegear.com.au/brands/Ugly-Fish.html','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '1','Polarised' => '1','Prescription' => '0','Safety' => '1'),
  array('ID' => '16','ClassName' => 'OnlineStore','Created' => '2012-08-30 12:59:03','LastEdited' => '2013-01-08 11:55:24','Title' => 'So Much Stuff','Email' => 'sales@somuchstuff.com.au','Website' => 'http://www.somuchstuff.com.au/shop/c/ugly-fish','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '17','ClassName' => 'OnlineStore','Created' => '2012-09-03 16:21:22','LastEdited' => '2012-09-03 16:21:22','Title' => 'The Helmet Warehouse','Email' => NULL,'Website' => 'https://www.thehelmetwarehouse.com.au/store.php?crn=214','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '1','Polarised' => '0','Prescription' => '0','Safety' => '0'),
  array('ID' => '18','ClassName' => 'OnlineStore','Created' => '2012-11-30 16:32:42','LastEdited' => '2012-11-30 16:44:45','Title' => 'Slashsport Shop','Email' => NULL,'Website' => 'http://www.slashsport.com/shop','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '22','ClassName' => 'OnlineStore','Created' => '2013-10-23 10:46:26','LastEdited' => '2013-10-23 10:46:26','Title' => 'Get Glasses','Email' => NULL,'Website' => 'http://www.getglasses.com.au/sunglasses/ugly-fish','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '23','ClassName' => 'OnlineStore','Created' => '2013-10-29 15:21:43','LastEdited' => '2013-10-29 15:21:43','Title' => 'Oz Tackle','Email' => NULL,'Website' => 'http://www.oztackle.com.au/','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '24','ClassName' => 'OnlineStore','Created' => '2014-03-06 16:33:07','LastEdited' => '2014-03-06 16:41:45','Title' => 'Land Based Fishing','Email' => 'contactus@landbasedfishing.com.au','Website' => 'https://landbasedfishing.com.au/','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '0','Polarised' => '1','Prescription' => '0','Safety' => '0'),
  array('ID' => '25','ClassName' => 'OnlineStore','Created' => '2014-04-02 10:57:52','LastEdited' => '2014-04-02 10:57:52','Title' => 'Pandemic Cycles ','Email' => NULL,'Website' => 'http://stores.ebay.com.au/pandemiccycles','PhoneNumber' => NULL,'FaxNumber' => NULL,'Riderz' => '1','Polarised' => '0','Prescription' => '0','Safety' => '0')
);
